// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QIKs4wXj3sYNgaqswPC-tw2XchWrc5w',
    appId: '1:872632915138:web:d69b5d9f2b91027f38975b',
    messagingSenderId: '872632915138',
    projectId: 'cheerify-8979b',
    authDomain: 'cheerify-8979b.firebaseapp.com',
    storageBucket: 'cheerify-8979b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASwHjXfGo5DT4Zy3cZao7Pe-8-PJpg4Co',
    appId: '1:872632915138:android:d34d64fe7ce05f8338975b',
    messagingSenderId: '872632915138',
    projectId: 'cheerify-8979b',
    storageBucket: 'cheerify-8979b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9BEd1NE075DjMjNhcsiNRskVRRnFaMys',
    appId: '1:872632915138:ios:79a2480eb9c4d82238975b',
    messagingSenderId: '872632915138',
    projectId: 'cheerify-8979b',
    storageBucket: 'cheerify-8979b.appspot.com',
    iosBundleId: 'com.example.cheerifyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9BEd1NE075DjMjNhcsiNRskVRRnFaMys',
    appId: '1:872632915138:ios:ac3ee1d262016c5738975b',
    messagingSenderId: '872632915138',
    projectId: 'cheerify-8979b',
    storageBucket: 'cheerify-8979b.appspot.com',
    iosBundleId: 'com.example.cheerifyFlutter.RunnerTests',
  );
}
